#ifndef MODBUS_REGS_H
#define MODBUS_REGS_H

#include <stdint.h>
#include <stdbool.h>
#include "error_handler.h"
#include "user_mb_app.h"
#include "mb.h"

/* modbus registers and bytes mapping */
#define MODBUS_HOLDING_START       S_REG_HOLDING_START
#define MODBUS_HOLDING_COUNT       S_REG_HOLDING_NREGS
#define MODBUS_INPUT_START         S_REG_INPUT_START
#define MODBUS_INPUT_COUNT         S_REG_INPUT_NREGS
#define MODBUS_COIL_START          S_COIL_START
#define MODBUS_COIL_COUNT          S_COIL_NCOILS
#define MODBUS_DISCRETE_START      S_DISCRETE_INPUT_START
#define MODBUS_DISCRETE_COUNT      S_DISCRETE_INPUT_NDISCRETES

/* user register indices */
enum {
  MODBUS_HOLDING_REG_PWM_DUTY = 0,
  MODBUS_HOLDING_REG_PWM_FREQUENCY,
  MODBUS_HOLDING_REG_STATUS,
  MODBUS_HOLDING_REG_FAULT_CODE,
  MODBUS_HOLDING_REG_RESERVED_4,
  MODBUS_HOLDING_REG_RESERVED_5,
  MODBUS_HOLDING_REG_RESERVED_6,
  MODBUS_HOLDING_REG_RESERVED_7,
  MODBUS_HOLDING_REG_RESERVED_8,
  MODBUS_HOLDING_REG_RESERVED_9,
  MODBUS_HOLDING_REG_RESERVED_10,
  MODBUS_HOLDING_REG_RESERVED_11,
  MODBUS_HOLDING_REG_RESERVED_12,
  MODBUS_HOLDING_REG_RESERVED_13,
  MODBUS_HOLDING_REG_RESERVED_14,
  MODBUS_HOLDING_REG_RESERVED_15,
};

enum {
  MODBUS_INPUT_REG_DEVICE_ID = 0,
  MODBUS_INPUT_REG_MEASUREMENT,
  MODBUS_INPUT_REG_TEMPERATURE,
  MODBUS_INPUT_REG_FIRMWARE_MAJOR,
  MODBUS_INPUT_REG_FIRMWARE_MINOR,
  MODBUS_INPUT_REG_RESERVED_5,
  MODBUS_INPUT_REG_RESERVED_6,
  MODBUS_INPUT_REG_RESERVED_7,
  MODBUS_INPUT_REG_RESERVED_8,
  MODBUS_INPUT_REG_RESERVED_9,
  MODBUS_INPUT_REG_RESERVED_10,
  MODBUS_INPUT_REG_RESERVED_11,
  MODBUS_INPUT_REG_RESERVED_12,
  MODBUS_INPUT_REG_RESERVED_13,
  MODBUS_INPUT_REG_RESERVED_14,
  MODBUS_INPUT_REG_RESERVED_15,
};

enum {
  MODBUS_COIL_PWM_ENABLE = 0,
  MODBUS_COIL_FAULT_RESET,
  MODBUS_COIL_RESERVED_2,
  MODBUS_COIL_RESERVED_3,
  MODBUS_COIL_RESERVED_4,
  MODBUS_COIL_RESERVED_5,
  MODBUS_COIL_RESERVED_6,
  MODBUS_COIL_RESERVED_7,
  MODBUS_COIL_RESERVED_8,
  MODBUS_COIL_RESERVED_9,
  MODBUS_COIL_RESERVED_10,
  MODBUS_COIL_RESERVED_11,
  MODBUS_COIL_RESERVED_12,
  MODBUS_COIL_RESERVED_13,
  MODBUS_COIL_RESERVED_14,
  MODBUS_COIL_RESERVED_15,
};

enum {
  MODBUS_DISCRETE_READY = 0,
  MODBUS_DISCRETE_RUNNING,
  MODBUS_DISCRETE_FAULT,
  MODBUS_DISCRETE_RESERVED_3,
  MODBUS_DISCRETE_RESERVED_4,
  MODBUS_DISCRETE_RESERVED_5,
  MODBUS_DISCRETE_RESERVED_6,
  MODBUS_DISCRETE_RESERVED_7,
  MODBUS_DISCRETE_RESERVED_8,
  MODBUS_DISCRETE_RESERVED_9,
  MODBUS_DISCRETE_RESERVED_10,
  MODBUS_DISCRETE_RESERVED_11,
  MODBUS_DISCRETE_RESERVED_12,
  MODBUS_DISCRETE_RESERVED_13,
  MODBUS_DISCRETE_RESERVED_14,
  MODBUS_DISCRETE_RESERVED_15,
};

ModbusError_t ModbusRegs_Init(void);
ModbusError_t ModbusRegs_Reset(void);

uint16_t *ModbusRegs_GetHoldingBuffer(void);
uint16_t *ModbusRegs_GetInputBuffer(void);
uint8_t *ModbusRegs_GetCoilBuffer(void);
uint8_t *ModbusRegs_GetDiscreteInputBuffer(void);

ModbusError_t ModbusRegs_GetHolding(uint16_t index, uint16_t *value);
ModbusError_t ModbusRegs_SetHolding(uint16_t index, uint16_t value);
ModbusError_t ModbusRegs_GetInput(uint16_t index, uint16_t *value);
ModbusError_t ModbusRegs_SetInput(uint16_t index, uint16_t value);
ModbusError_t ModbusRegs_GetCoil(uint16_t index, bool *state);
ModbusError_t ModbusRegs_SetCoil(uint16_t index, bool state);
ModbusError_t ModbusRegs_GetDiscrete(uint16_t index, bool *state);
ModbusError_t ModbusRegs_SetDiscrete(uint16_t index, bool state);

#endif /* MODBUS_REGS_H */
